version: '3.8'

services:
  app:
    container_name: fake_news_detector
    build: ./
    depends_on:
      - db
    ports:
      - ${APP_HOST_PORT}:80
    restart: always
    env_file:
      - .env
  db:
    container_name: news_db
    image: postgres
    environment:
      - POSTGRES_DB=news_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    restart: always

